name: Demo
on: [push]

jobs:
  ubuntu-run:
    runs-on: ubuntu-18.04

    env:
      greetname: World

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Greet user
        run: |
          echo Hello $greetname on $RUNNER_OS
          ls -a
          sleep 15
