name: Demo
on: [push]

jobs:
  ubuntu-run:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        device: ['desktop', 'mobile']
        browser: ['firefox', 'chrome']
  
    env:
      greetname: World

    steps:
      - name: Greet user
        run: |
          echo ${{ matrix.device }} ${{ matrix.browser }}
          echo Hello $greetname on $RUNNER_OS
          pwd
          ls -a
          sleep 15

  macos-run:
    runs-on: macos-latest

    needs: ubuntu-run

    env:
      greetname: World

    steps:
      - name: Greet user
        run: |
          echo Hello $greetname on $RUNNER_OS
          sleep 15
