name: Demo
on: [push]

jobs:
  ubuntu-run:
    runs-on: ubuntu-18.04

    env:
      greetname: World

    steps:
      - name: Greet user
        run: echo Hello $greetname on $RUNNER_OS

jobs:
  macos-run:
    runs-on: macos-latest

    env:
      greetname: World

    steps:
      - name: Greet user
        run: echo Hello $greetname on $RUNNER_OS